# This is a simplified config where the rest of the settings are omitted and will be set by default.
# See https://gate.minekube.com/guide/config/ for the full configuration options.
config:
  bind: 0.0.0.0:25565
  onlineMode: true

  # Player information forwarding to backend servers
  # REQUIRED: Configure this for your backend server to accept connections
  forwarding:
    mode: legacy # Options: none, legacy, velocity, bungeeguard
    # For velocity/bungeeguard, add a secret:
    # secret: "your-secret-key-here"

  servers:
    server1: localhost:25566
    server2: localhost:25567
  try:
    - server1
    - server2
  # Disabling it allows our global-chat plugin to cancel messages.
  forceKeyAuthentication: false

  # Configure the response for server list pings.
  status:
    # The message of the day in legacy '§' format or modern text component '{"text":"...", ...}' json.
    motd: |
      §bGate Proxy x GCP-Controller
      §bVisit ➞ §fgithub.com/Finn24-09/gate-gcp-controller
    # The maximum players shown (is not the actual player limit!).
    showMaxPlayers: 100
    # The server image (optimal 64x64); a path of an image file or the base64 data uri.
    # favicon:
    # Whether to log ping requests in the console.
    logPingRequests: false
    # Whether the proxy should present itself as Forge/FML-compatible server.
    announceForge: false

  # Whether to register builtin commands on proxy start.
  # Default: true
  builtinCommands: true
  # Whether players require permissions to
  # execute a builtin proxy command like /server.
  # Ignore this if `builtinCommands` is set to false.
  # (This should be set to true in production environments.)
  # Default: false
  requireBuiltinCommandPermissions: true

# Whitelist Plugin Configuration
# Controls which players can connect to the proxy
whitelist:
  # Whether the whitelist is enabled
  enabled: true
  # Message shown to non-whitelisted players when kicked
  kickMessage: "You are not whitelisted on this server!"
  # Path to the whitelist file (uses Minecraft's official format)
  whitelistFile: "whitelist.json"
  # List of operator UUIDs who can manage the whitelist
  # Get your UUID from https://mcuuid.net/ or check server logs when you connect
  operators:
    - "069a79f4-44e9-4726-a5be-fca90e38aaf5" # Replace with your UUID

# GCP Controller Plugin Configuration
# Automatically starts/stops GCP Compute Engine instances based on player activity
gcpController:
  # Required: Your GCP project ID
  projectId: "my-gcp-project"

  # Required: The GCP zone where your instance is located (e.g., us-central1-a, europe-west1-b)
  zone: "us-central1-a"

  # Required: The name of your GCP Compute Engine instance
  instanceName: "minecraft-server"

  # Required: The server name from config.servers that corresponds to this GCP instance
  serverAddress: "server1"

  # Optional: Path to GCP service account credentials JSON file
  # Leave empty or comment out to use Application Default Credentials (ADC)
  # ADC works automatically when running on GCP Compute Engine with a service account
  # credentialsPath: "/credentials/gcp-key.json"

  # Optional: Minutes of inactivity before automatically stopping the server (default: 30)
  idleTimeoutMinutes: 30

  # Optional: Cooldown period in minutes after starting to prevent duplicate start requests (default: 5)
  startupThresholdMinutes: 5

  # Optional: Minutes to wait for a player to join after server startup before automatic shutdown (default: 15)
  # This prevents unnecessary costs when a player triggers the server to start but never actually joins.
  # If no player connects to the game server within this timeframe after startup, the instance will be
  # automatically shut down to save costs. Set to 0 to disable this safety feature.
  noJoinTimeoutMinutes: 15

  # Optional: Message shown to players when the server is starting
  startingMessage: "Server is starting up! Please wait 30-60 seconds and try again."
