version: '3.8'

services:
  gate-proxy:
    image: ghcr.io/finn24-09/gate-gcp-controller:latest
    container_name: gate-gcp-controller
    ports:
      - "25565:25565"
    volumes:
      # Mount custom config.yml (edit this file with your GCP settings)
      - ./config.yml:/config.yml:ro
      # Mount whitelist.json for persistence (create with: echo "[]" > whitelist.json)
      - ./whitelist.json:/whitelist.json
      # Mount GCP credentials (OPTIONAL - only needed if not using ADC)
      # Comment out the line below if running on GCP with a service account
      # - ${GCP_CREDENTIALS_FILE:-./gcp-key.json}:/credentials/gcp-key.json:ro
    restart: unless-stopped
    networks:
      - minecraft

networks:
  minecraft:
    driver: bridge
